config/routes.rb
Rails.application.routes.draw do



  #管理者用
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  get 'admin' => 'admin/homes#top'
  namespace :admin do
    resources :posts, only: [:show, :edit, :update, :destroy, :index] do
     resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update]
  end

  #ユーザー
  devise_for :user, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
   }

  scope module: :public do
    resources :users, only: [:show]
    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
     resources :post_comments, only: [:create, :destroy]
     resources :bookmarks, only: [:create, :destroy, :index]
    end
    get '/user/information/edit' => 'users#edit'
    patch '/user/information' => 'users#update'
    get 'search' => 'posts#search'
    get '/search_tag' => 'posts#search_tag'
  end

  namespace :public do
    get 'post_comments/create'
    get 'post_comments/destroy'
  end
  #get 'post_comments/create'
  #get 'post_comments/destroy'



  #ゲストユーザーログイン
 devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'

  end

  root to: 'public/homes#top'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  validates :image, presence: true
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags,through: :post_tags
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

def self.search(keyword)
  where(["title like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
end


  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end


end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @posts = @post.post_comments
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to admin_posts_path(@post.id)

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = '投稿を削除しました'
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :introduction, :tourist_spot, :image)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/edit.html.erb
<div class="container-sm">
  <div class="row mt-4">
    <div class="col-4">
      <h4>投稿内容編集</h4>
    </div>
  </div>
  <%= form_with model: @post, url: admin_post_path(@post.id), method: :patch do |f| %>
  <div class="row mt-2">
    <%= f.label :タイトル, class: "h5 col-3 text-secondary" %>
    <%= f.text_field :title %>
  </div>
  <div class="row mt-2">
    <%= f.label :本文, class: "h5 col-3 text-secondary" %>
    <%= f.text_area :introduction %>
  </div>
  <div class="row mt-2">
    <%= f.label :観光地名, class: "h5 col-3 text-secondary" %>
    <%= f.text_area :tourist_spot %>
  </div>
  <div class="row mt-2">
    <%= f.label :写真, class: "h5 col-3 text-secondary" %>
    <%= f.file_field :image, accept: "image/*" %>
  </div>
  <div class="row mt-4">
    <%= f.submit "保存", class: "col-1 offset-2 btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row mt-3 text-success">
    <h4>投稿一覧</h4>
  </div>
  <div class="row mt-2">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th scope="col">投稿者</th>
          <th scope="col">タイトル</th>
          <th scope="col">内容</th>
          <th scope="col">コメント数</th>
          <th scope="col">投稿日</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each_with_index do |post, i| %>
          <tr>
            <th scop="row"><%= i+1 %></th>
            <td><%= link_to post.user.name, admin_user_path(post.user.id) %></td>
            <td><%= link_to post.title, admin_post_path(post.id) %></td>
            <td><%= post.introduction %></td>
            <td><%= post.post_comments.count %></td>
            <td><%= post.created_at.strftime('%Y/%m/%d/ %H:%M') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/posts/show.html.erb
<%= flash[:notice] %>
<div class="row-sm">
  <div class="col-sm-8">
     <div class="card-post">
      <div class="card w-50 offset-6 mt-5 shadow-lg">
       <%= image_tag @post.image, class: "card-imag-top" %>
       <div class="card-body">
        <h5 class="card-title"><%= @post.title %></h5>
        <p class="card-text"><%= @post.introduction %></p>
        <%= link_to @post.user.name, admin_user_path(@post.user.id), class: "btn btn-info" %>
        <%= link_to "投稿内容編集", edit_admin_post_path(@post.id), class: "ml-2 btn btn-secondary" %>
        <%= link_to "投稿削除", admin_post_path(@post.user.id), method: :delete, class: "ml-2 btn btn-danger" %>
       </div>
      </div>
     </div>
  </div>
  <div class="col-sm-5 offset-3 mt-5">
   <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
         <th scope="col">コメント</th>
         <th scope="col">投稿者</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each_with_index do |post, i| %>
      <tr>
        <th scop="row"><%= i+1 %></th>
        <td><%= post.comment %></td>
        <td><%= post.user.name %></td>
        <td><%= link_to "削除", admin_post_post_comment_path(post.post,post), method: :delete %></td>
      </tr>
      <% end %>
    </tbody>
   </table>
  </div>
</div>