config/routes.rb
Rails.application.routes.draw do



  #管理者用
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  get 'admin' => 'admin/homes#top'
  namespace :admin do
    resources :posts, only: [:show, :edit, :update, :destroy, :index] do
     resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update]
  end

  #ユーザー
  devise_for :user, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
   }

  scope module: :public do
    resources :users, only: [:show]
    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
     resources :post_comments, only: [:create, :destroy]
     resources :bookmarks, only: [:create, :destroy, :index]
    end
    get '/user/information/edit' => 'users#edit'
    patch '/user/information' => 'users#update'
    get 'search' => 'posts#search'
    get '/search_tag' => 'posts#search_tag'
  end

  namespace :public do
    get 'post_comments/create'
    get 'post_comments/destroy'
  end
  #get 'post_comments/create'
  #get 'post_comments/destroy'



  #ゲストユーザーログイン
 devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'

  end

  root to: 'public/homes#top'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 def self.guest
   find_or_create_by!(email: "guest@aiu.com") do |user|
     user.password = SecureRandom.urlsafe_base64
     user.name = "ゲスト"
     user.address = "ゲスト大分県"
   end
 end

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_one_attached :image




end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    #@post = Post.find(params[:id])
    @users = @user.posts
  end

  def edit
    @user = User.find(params[:id])
    @users = @user.posts
  end

  def update
    @user = User.find(params[:id])
    #@users = @user.posts
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end


  private

  def user_params
    params.require(:user).permit(:nick_name, :email, :prefectural, :city)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="badge bg-light">
      <h4><%= @user.name %>さんの会員情報編集</h4>
    </div>
  </div>
  <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
  <div class="row mt-2">
    <%= f.label :会員ID, class: " h5 col-3" %>
    <%= @user.id %>
  </div>
  <div class="row mt-2">
    <%= f.label :登録名, class: " h5 col-3" %>
    <%= f.text_field :name %>
  </div>
  <div class="row mt-2">
    <%= f.label :メールアドレス, class: "h5 col-3" %>
    <%= @user.email %>
  </div>
  <div class="row mt-2">
    <%= f.label :所在地, class: "h5 col-3" %>
    <%= f.text_field :address %>
  </div>
  <%= f.submit '変更を保存', class: "col-2 mt-3 offset-3 btn btn-success" %>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row mt-3 offset-1">
    <div class="badge bg-light">
      <h4><%= @user.name %>さんの詳細ページ</h4>
    </div>
    <div class="col">
      <%= link_to "会員情報編集する", edit_admin_user_path(@user.id), class: "offset-3 btn btn-success" %>
    </div>
  </div>
  <div class="row mt-4 offset-2">
    <div class="col-2 badge bg-light">
      <h5>会員ID</h5>
    </div>
    <div class="col-4 ml-4">
      <h5><%= @user.id %></h5>
    </div>
  </div>
  <div class="row mt-2 offset-2">
    <div class="col-2 badge bg-light">
      <h5>登録名</h5>
    </div>
    <div class="col-4 ml-4">
      <h5><%= @user.name %></h5>
    </div>
  </div>
  <div class="row mt-2 offset-2">
    <div class="col-2 badge bg-light">
      <h5>メールアドレス</h5>
    </div>
    <div class="col-4 ml-4">
      <h5><%= @user.email %></h5>
    </div>
  </div>
  <div class="row mt-2 offset-2">
    <div class="col-2 badge bg-light">
      <h5>登録住所</h5>
    </div>
    <div class="col-4 ml-4">
      <h5><%= @user.address %></h5>
    </div>
  </div>
  <div class="row mt-2 offset-2">
    <div class="col-2 badge bg-light">
      <h5>登録日</h5>
    </div>
    <div class="col-4 ml-4">
      <h5><%= @user.created_at.strftime('%Y/%m/%d/ %H:%M') %></h5>
    </div>
  </div>
  <div class="row mt-2 offset-2">
    <table class="table table-success table-striped">
      <thead>
        <tr>
          <th>投稿日</th>
          <th>タイトル</th>
          <th>内容</th>
          <th>写真</th>
          <th>タグ</th>
          <th>削除</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.created_at.strftime('%Y/%m/%d %H:%M') %></td>
          <td><%= link_to user.title, admin_post_path(user.id) %></td>
          <td><%= user.introduction %></td>
          <td><%= image_tag user.image, size: "100x100" %></td>
          <td><%= user.tags.map(&:name).join(', ') %></td>
          <td><%= link_to "削除", admin_post_path(user.id), method: :delete, class: "col ml-2 btn btn-danger" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>