config/routes.rb
Rails.application.routes.draw do



  #管理者用
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  get 'admin' => 'admin/homes#top'
  namespace :admin do
    resources :posts, only: [:show, :edit, :update, :destroy, :index] do
     resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update]
  end

  #ユーザー
  devise_for :user, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
   }

  scope module: :public do
    resources :users, only: [:show]
    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
     resources :post_comments, only: [:create, :destroy]
     resources :bookmarks, only: [:create, :destroy, :index]
    end
    get '/user/information/edit' => 'users#edit'
    patch '/user/information' => 'users#update'
    get 'search' => 'posts#search'
    get '/search_tag' => 'posts#search_tag'
  end

  namespace :public do
    get 'post_comments/create'
    get 'post_comments/destroy'
  end
  #get 'post_comments/create'
  #get 'post_comments/destroy'



  #ゲストユーザーログイン
 devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'

  end

  root to: 'public/homes#top'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  validates :image, presence: true
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags,through: :post_tags
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

def self.search(keyword)
  where(["title like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
end


  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end


end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true, length:{maximum:120}
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  validates :post_id, presence: true
  validates :tag_id, presence: true

  
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :post_tags
  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 def self.guest
   find_or_create_by!(email: "guest@aiu.com") do |user|
     user.password = SecureRandom.urlsafe_base64
     user.name = "ゲスト"
     user.address = "ゲスト大分県"
   end
 end

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_one_attached :image




end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
   @users = User.all
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @posts = @post.post_comments
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to admin_posts_path(@post.id)

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = '投稿を削除しました'
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :introduction, :tourist_spot, :image)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    #@post = Post.find(params[:id])
    @users = @user.posts
  end

  def edit
    @user = User.find(params[:id])
    @users = @user.posts
  end

  def update
    @user = User.find(params[:id])
    #@users = @user.posts
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end


  private

  def user_params
    params.require(:user).permit(:nick_name, :email, :prefectural, :city)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
 def sidebar_link_item(name, path)
    class_name = 'channel'
    class_name << ' active' if current_page?(path)

    content_tag :li, class:class_name do
      link_to name, path, class: 'channel_name'
    end
 end
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="listings">
  <div class="listings_channels">
    <h4 class="listings_header">メニュー</h4>
    <ul class="channel_list">
      <h5></h5>
      <h5></h5>
      <h5></h5>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
     <div class="container-sm text-center">
        <div class="row mt-4">
          <% if  user_signed_in? && current_user.email == "guest@aiu.com" %>
            <button type="button" class="btn btn-outline-secondary mx-2">
              <%= link_to "新規登録", new_user_registration_path %>
            </button>
            <button type="button" class="btn btn-outline-secondary mx-2">
              <%= link_to "投稿一覧", posts_path %>
            </button>
            <button type="button" class="btn btn-outline-primary mx-2">
              <%= link_to "マイページ", user_path(@user) %>
            </button>
            <button type="button" class="btn btn-outline-primary mx-2">
             <%= link_to "top", root_path %>
            </button>
            <button type="button" class="btn btn-outline-primary mx-2">
             <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </button>
            <%= flash[:notice] %>
            <div class="col-4">
              <p>ゲストログイン中</p>
            </div>
           <% elsif user_signed_in? %>
             <button type="button" class="btn btn-outline-primary mx-2">
              <%= link_to "top", root_path %>
             </button>
             <button type="button" class="btn btn-outline-primary mx-2">
               <%= link_to "マイページ", user_path(current_user) %>
             </button>
             <button type="button" class="btn btn-outline-primary mx-2">
               <%= link_to "みんなの投稿", posts_path %>
             </button>
             <button type="button" class="btn btn-outline-primary mx-2">
               <%= link_to "新規投稿", new_post_path %>
             </button>
             <button type="button" class="btn btn-outline-primary mx-2">
                <%= link_to "ブックマーク一覧", post_bookmarks_path(current_user) %>
             </button>
             <button type="button" class="btn btn-outline-primary mx-2">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
             </button>
          <% elsif admin_signed_in? %>
           <button type="button" class="btn btn-outline-primary mx-2">
             <%= link_to "Top", admin_path %>
           </button>
           <button type="button" class="btn btn-outline-primary mx-2">
             <%= link_to "投稿一覧", admin_posts_path %>
           </button>
           <button type="button" class="btn btn-outline-primary mx-2">
             <%= link_to "会員一覧", admin_path %>
           </button>
           <button type="button" class="btn btn-outline-primary mx-2">
             <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
           </button>
           <div class="col-4 text-danger">
             <p>管理者としてログイン中</p>
           </div>
          <% else %>
            <button type="button" class="btn btn-outline-secondary mx-2">
               <%= link_to "ログイン", new_user_session_path %>
            </button>
            <button type="button" class="btn btn-outline-secondary mx-2">
              <%= link_to "新規登録", new_user_registration_path %>
            </button>
            <button type="button" class="btn btn-outline-secondary mx-2">
           　<%= link_to 'ゲストログイン（閲覧用）', public_guest_sign_in_path, method: :post %>
            </button>
          <% end %>
        </div>
      </div>
    </header>
      <%= yield %>
    </div>
  </body>
</html>